-- Record only. The canonical greenfield script is:
--   supabase/bootstrap.sql
--
-- Apply that single file in the Supabase SQL Editor on any empty project.
-- Incremental history remains in this migrations/ folder for reference;
-- you do not need to run those files in order if you use bootstrap.sql.
--
-- Tables covered by bootstrap.sql:
--   users, events, event_rsvps, documents, board_members, announcements,
--   initiatives (+ is_legacy), initiative_gallery, gallery_media,
--   pulse_forms, pulse_responses, page_sections, feedback, contact_messages,
--   milestones, ideas, idea_votes, idea_comments
-- Plus RLS + seed page_sections / sample initiatives / board / milestones.
